#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


RobotMap::RobotMap(){
	
	DRIVESTICK_JOYSTICK = 0;
	 SHOOTSTICK_JOYSTICK = 1;
	
	 LEFT_FRONT_MOTOR = 0;
	 LEFT_REAR_MOTOR = 1;
	 RIGHT_FRONT_MOTOR = 2;
	 RIGHT_REAR_MOTOR = 3;
	
	 SHOOTER_LEFT_MOTOR = 4;
	 SHOOTER_RIGHT_MOTOR = 5;
	 SHOOTER_LIFT_MOTOR = 6;
	
	 LEFT_DRIVE_ENCODER_A = 4;
	 LEFT_DRIVE_ENCODER_B = 5;
	
	 RIGHT_DRIVE_ENCODER_A = 2;
	 RIGHT_DRIVE_ENCODER_B = 3;
	
	 SHOOTER_ENCODER_A = 0;
	 SHOOTER_ENCODER_B = 1;
	
//	 LIFT_ENCODER_A = 6;
//	 LIFT_ENCODER_B = 7;
	
	 COMPRESSOR = 0;
	
	 SHIFTER_SOLENOID_A = 2;
	 SHIFTER_SOLENOID_B = 3;
	
	 SHOOTER_SOLENOID_A = 0;
	 SHOOTER_SOLENOID_B = 1;
	
}
